#!/bin/bash
TOOL_NAME="organize"
LOG_FOLDER=.
SOURCE_FOLDER=~/OneDrive/Descargas
TARGET_FOLDER=~/OneDrive/Descargas
DATA_FOLDER=~/OneDrive/Descargas
ORGANIZE_COMMAND="sim"
ORGANIZE_CONFIG==../samples/config.yaml
